name: Update Fork

on:
  push:
    branches:
      - main

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source repository
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure the entire history is fetched

      # Add the fork repository as a remote
      - name: Add fork remote
        run: |
          git remote add fork https://x-access-token:${{ secrets.FORK_PAT }}@github.com/stepsen89/wcc-frontend.git
          git fetch fork

      # Push changes to the fork
      - name: Push to fork
        run: |
          git push fork main:main
